### ISSUE TITLE
Stock Price difference API and NASDAQ

### ISSUE THREAD

**Issue by TheEpicBigBoss** [antoinevulcain/Financial-Modeling-Prep-API#28]
Hi,
I noticed that the stock price from your API is different from some endpoints and different from the Nasdaq website or other endpoints that access Nasdaq.

For example symbol: CBSHP
(all values from about 6pm New York Time so 2 hours after market closed. (23:00 in Europe)

https://financialmodelingprep.com/api/v3/company/stock/list     price: 25,35$ correct

https://financialmodelingprep.com/api/v3/stock/real-time-price
https://financialmodelingprep.com/api/v3/stock/real-time-price/CBSHP     price: 25,26$ wrong
https://financialmodelingprep.com/api/v3/historical-chart/Xmin/CBSHP     also 25,26$

Nasdaq / Google / Onvista (Today 10.03.2020):
![NASDAQ](https://user-images.githubusercontent.com/23483481/76364929-61446200-6326-11ea-9821-c77b617dd38a.PNG)
![CBSHP](https://user-images.githubusercontent.com/23483481/76364942-66a1ac80-6326-11ea-8d35-26dd45457bda.PNG)
![10 03 2020 23h15](https://user-images.githubusercontent.com/23483481/76364944-69040680-6326-11ea-8b88-01aacc22f569.PNG)

Could this may be happening because the last trade was at 16:00:01 so 1 second past 4pm?

**Comment by antoinevulcain** [comment]
if you use this endpoint:

https://financialmodelingprep.com/api/v3/quote/CBSHP

You will have the good value, I'm checking now for the other endpoints

**Comment by antoinevulcain** [comment]
Ok I found the issue:

https://financialmodelingprep.com/api/v3/company/stock/list gets updated with the same statement as https://financialmodelingprep.com/api/v3/quote/CBSHP which includes a condition very tricky explained here:

https://github.com/antoinevulcain/Financial-Modeling-Prep-API/issues/27

which check if the market is open and must have not catch the millisecond where it went to 16:00:00 because we have some complex multi Thread condition to check but I will update the code to reflect this change.

This url :

https://financialmodelingprep.com/api/v3/quote/CBSHP

will always have the good data since it is updated in websocket and does not check for market hours you can rely on it at all times.

for the historical I will make the update to catch the last change, let me know if you see this issue happening again.

for https://financialmodelingprep.com/api/v3/stock/real-time-price and https://financialmodelingprep.com/api/v3/stock/real-time-price/CBSHP it is a bit tricker it will take more time I have to investigate but in the mean time you have this one https://financialmodelingprep.com/api/v3/quote/CBSHP.

I will do the changes asap, thanks for pointing out the issue

**Comment by TheEpicBigBoss** [comment]
Ok thats good.
Then I will mainly use the Quote endpoint / or use the price from the company stock list.

On the other endpoints I will keep an eye on it and let you know if this issue still remains.
Thanks for working on it and the fast response.
(A little bit off-topic but will this API still remain free? Little worried because you launched fmpcloud.io with only limited free api calls or paid option.)

**Comment by antoinevulcain** [comment]
Perfect. sounds good.

No worries I'm always working on making this API better.

Yes this API **will remain free and actively maintain by us**.
 
We have decided to launched https://fmpcloud.io/ due to a lot of custom demand such as RSS feed, 13-F, and for response quality (i.e you can see for financial statement that the response is more structured and have more fields), but we made it accessible with a free tier and at a very low price for anyone to access it and not create complicated plans based on API calls limitations where you have to plan on the number of calls in advance that you have to make.
It is one plan unlimited access, it is a way of supporting us, but don't worry we will **maintain and keep this API free and strongly reliable**.

**Comment by antoinevulcain** [comment]
-> Quote endpoint as new reference
